services:
  - type: web
    name: insta-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: VERIFY_TOKEN
        sync: false
      - key: META_ACCESS_TOKEN
        sync: false
      - key: APP_SECRET
        sync: false
      - key: IG_BUSINESS_ACCOUNT_ID
        sync: false
      - key: GRAPH_API_VERSION
        sync: false
